<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EngineIO.Client\EngineIO.Client.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Update="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
    </ItemGroup>

</Project>
